apiVersion: v1
kind: Service
metadata:
  name: "pgbouncer"
  labels:
    name: "pgbouncer"
    criticality: high
    web-facing: "no"
    data-classification: "no"
    app.kubernetes.io/name: "pgbouncer"
spec:
  type: "ClusterIP"
  selector:
    name: "pgbouncer"
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432